---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
        - name: medicure-container
          image: nmenakshy199/medicure-project:latest
          ports:
            - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: medicure-service
spec:
  selector:
    app: medicure
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: NodePort
